### ISSUE TITLE
Create TS-Bot

### ISSUE THREAD

**Issue by ghost** [Manebot/ts3#1]
Hello, I have a question: How can I create a bot with this "system"?
Best regards,
Patrick

**Comment by Manevolent** [comment]
Patrick,

Documentation is a little lacking at this time, apologies for that.

https://hub.docker.com/r/manevolent/manebot

This Docker container is currently what I would recommend using.  In order to get a running instance of that on a Teamspeak3 server, you would need to run the following command to first install the plugin represented by this Git repository:

`plugin install ts3`

Then, to join a server, you would use the command built-in to the plugin, which is defined here:
https://github.com/Manevolent/manebot-ts3/blob/master/src/main/java/io/manebot/plugin/ts3/command/TeamspeakCommand.java

Say you wanted to add a server named with the ID **myserver**
`teamspeak server add myserver myserver.com`
`teamspeak server enable myserver`

At this point, you should see the bot in the server.  To change its nickname,
`teamspeak server set myserver nickname My Teamspeak Bot`

To add music playback features,
`plugin install music`

You can then use `track play` to play tracks -- keep in mind that, in Teamspeak, the bot should respond to commands that start with a period (.).

There may be more steps to this, as it's been a minute since I set one of these up (I am working on this project actively, but haven't had a lot of time lately).  Let me know if you run into any problems and we can figure that out

**Comment by ghost** [comment]
And will there be an API for it?
Like to start a Bot with a Java-Programm?
